#!/bin/bash
# One-click commit + push of the typography polish to Website/style.css
# Generated by Claude — double-click to run.

set -e
cd "$(dirname "$0")" || { echo "ERROR: cannot cd to script directory"; exit 1; }

echo "==> Working directory: $(pwd)"

# Clean up any orphan git lock files
echo "==> Clearing any stale git locks..."
rm -f .git/index.lock .git/HEAD.lock .git/refs/heads/main.lock 2>/dev/null || true

# Stage only the style.css change
echo "==> Staging Website/style.css..."
git add Website/style.css

# Check there's actually something to commit
if git diff --cached --quiet; then
  echo "==> Nothing to commit on Website/style.css (already up to date)."
else
  echo "==> Creating commit..."
  git commit -m "Polish public-page typography & spacing toward Apple-grade hierarchy

- Add unified type-scale tokens (display, title-1, lede, body, eyebrow)
- Add leading and tracking scales as CSS custom properties
- Body line-height 1.6 → 1.5; add text-rendering + font-feature-settings
- Section vertical padding 56/72 → 96/112; add 1024px breakpoint
- Standardize hero/section h2 onto shared display tokens
- Lede paragraphs 17px → 19px with refined leading
- Tabular numerals + display tracking on stat strip and pricing-price
- Wider hero text columns and more breathing room around section headers"
fi

# Sync with remote (diverged: 1 local + 8 remote commits)
echo "==> Pulling remote (rebase) to sync..."
git pull --rebase

# Push
echo "==> Pushing to origin/main..."
git push

echo ""
echo "✅ Done. yalla.house will rebuild on GitHub Pages in ~1 minute."
echo ""
echo "Press any key to close this window..."
read -n 1 -s
