/* ============================================================
   YALLA.HOUSE — i18n Language Switcher
   Auto-detects: DE browser → German, else English
   Manual override stored in localStorage (yh_lang)
   ============================================================ */

'use strict';

var TRANSLATIONS = {

  /* ══════════════════════════════════════════════════════════
     SHARED — Header / Nav / Footer (used on every page)
  ══════════════════════════════════════════════════════════ */
  en: {
    'nav.services':         'Services &amp; Pricing',
    'nav.about':            'About',
    'nav.list':             'List Your Place',
    'nav.signin':           'Sign In ▾',
    'menu.label':           'Sign in as',
    'menu.owner.name':      'Owner',
    'menu.owner.desc':      'Listings, viewings &amp; offers',
    'menu.hunter.name':     'Home Hunter',
    'menu.hunter.desc':     'Browse &amp; book viewings',
    'menu.admin.name':      'Admin',
    'menu.admin.desc':      'Platform management',
    'menu.agent.name':      'Field Agent',
    'menu.agent.desc':      'Jobs &amp; on-site reports',
    'footer.tagline':       'No fees. No commission.',
    'footer.meta':          'Yalla.House GmbH<br />Registered in Germany.',
    'footer.col1.h4':       'Policies',
    'footer.privacy':       'Privacy Policy',
    'footer.terms':         'Terms of Service',
    'footer.cookie':        'Cookie Policy',
    'footer.col2.h4':       'Legal &amp; Compliance',
    'footer.gdpr':          'GDPR &amp; Safety',
    'footer.security':      'Security &amp; Data Protection',
    'footer.imprint':       'Imprint',
    'footer.col3.h4':       'Contact',
    'footer.copyright':     '&#169; 2025 Yalla.House GmbH. All rights reserved.',
    'footer.portals':       'Listed on Rightmove &bull; Zoopla',

    /* ── INDEX — Hero ── */
    'hero.badge':           'Now live in Germany',
    'hero.h1':              'Sell your home.<br />Keep every <span class="accent">euro</span>.',
    'hero.p':               'No agent fees. No commission. Professional tools, real buyers, and full control — for a flat, transparent fee.',
    'hero.proof1':          '<strong>400+</strong> sellers across Germany',
    'hero.proof2':          'Listed on <strong>Rightmove &amp; Zoopla</strong>',
    'hero.proof3':          '<strong>5&#9733;</strong> seller satisfaction',
    'login.title':          'Sign in to your dashboard',
    'login.owner.name':     'Owner',
    'login.owner.desc':     'Manage listings, viewings &amp; offers',
    'login.hunter.name':    'Home Hunter',
    'login.hunter.desc':    'Browse properties &amp; book viewings',
    'login.admin.name':     'Admin',
    'login.admin.desc':     'Platform management &amp; oversight',
    'login.agent.name':     'Field Agent',
    'login.agent.desc':     'Jobs, viewings &amp; on-site reports',
    'login.new':            'New? Create account &#8594;',
    'portals.label':        'Listed on',

    /* ── INDEX — Stats ── */
    'stat1.value':   '&#8364;0',
    'stat1.label':   'Commission — you keep 100% of your sale price',
    'stat2.value':   '48h',
    'stat2.label':   'Average time to go live on Rightmove &amp; Zoopla',
    'stat3.value':   '69%',
    'stat3.label':   'Of sellers want weekly automated progress updates',
    'stat4.value':   '&#8364;8k+',
    'stat4.label':   'Average saving vs traditional agent on a &#8364;400k sale',

    /* ── INDEX — How it works ── */
    'hiw.tag':    'How it works',
    'hiw.h2':    'From listing to sold — in four steps',
    'hiw.p':     'A clear, agent-free process. You stay in control at every stage.',
    'step1.h4':  'List Your Place',
    'step1.p':   'Answer a few simple questions. Upload photos, add details, and pick your services — all in under 20 minutes.',
    'step2.h4':  'Go Live on Portals',
    'step2.p':   'Your property appears on Rightmove, Zoopla, and more. We sync status changes automatically — no ghost listings.',
    'step3.h4':  'Manage Viewings &amp; Offers',
    'step3.p':   'Buyers book directly from live slots you set. Review offers in your dashboard, with full visibility.',
    'step4.h4':  'Complete the Sale',
    'step4.p':   'Legal support, document storage, and a sign-off checklist — everything needed to reach notary and completion.',
    'step5.h4':  'Monitor Performance',
    'step5.p':   'Weekly updates, buyer funnel data, agent response times. See exactly what&#39;s happening with your sale.',
    'step6.h4':  'Close the Deal',
    'step6.p':   'Documents, milestones, legal handoff — everything you need to reach notary and completion smoothly.',

    /* ── INDEX — Services ── */
    'svc.tag':  'Services',
    'svc.h2':   'Everything you need to sell',
    'svc.p':    'Pick exactly what you need. No bundles forced on you.',
    'svc1.h3':  'Professional Photography',
    'svc1.p':   'Stunning listing photos shot by local professionals. Hero image rules included for maximum portal CTR.',
    'svc2.h3':  '360° Virtual Tour',
    'svc2.p':   'Interactive 3D scan so buyers can explore your home before booking — fewer wasted viewings.',
    'svc3.h3':  'Floorplan Creation',
    'svc3.p':   'Accurate, publication-ready floorplans. Required by portals for premium placement.',
    'svc4.h3':  'Legal Support',
    'svc4.p':   'Notary referrals, document checks, and guidance at every legal milestone.',
    'svc5.h3':  'For Sale Board',
    'svc5.p':   'Branded yard sign delivered and installed. Still the #1 local lead generator.',
    'svc6.h3':  'Weekly Progress Reports',
    'svc6.p':   'Auto-generated seller update every 7 days — enquiries, viewings, feedback, and next steps.',
    'svc.cta':  'See All Services &amp; Pricing',

    /* ── INDEX — Clarity Index ── */
    'clarity.tag':      'Yalla Clarity Index',
    'clarity.h2':       'What sellers &amp; buyers really experience',
    'clarity.p':        'Survey of 400 German home movers — the pain points Yalla.House eliminates.',
    'clarity1.p':       'of buyers say slow or no reply is their #1 frustration',
    'clarity2.p':       'hit &ldquo;ghost status&rdquo; — homes listed as available that were already reserved',
    'clarity3.p':       'of sellers felt &ldquo;in the dark&rdquo; about what was happening week to week',
    'clarity4.suffix':  'min',
    'clarity4.p':       'per vendor per week saved with automated weekly updates',

    /* ── INDEX — Testimonials ── */
    'test.tag':    'What people say',
    'test.h2':     'The experience speaks for itself',
    'test1.q':     'If I could just pick a slot that actually exists, I&#39;d view twice as many homes. Yalla finally made that possible.',
    'test1.name':  'Jamie M.',
    'test1.role':  'Home Hunter, 32 — Berlin',
    'test2.q':     'Send me a weekly snapshot so I don&#39;t have to chase. That&#39;s all I want. Yalla does this automatically — game changer.',
    'test2.name':  'Sarah H.',
    'test2.role':  'Owner, 48 — Munich',
    'test3.q':     'I saved over &#8364;12,000 in agent fees. The portal listings were live in 48 hours and the dashboard is brilliant.',
    'test3.name':  'Ravi P.',
    'test3.role':  'Owner, 41 — Frankfurt',

    /* ── INDEX — CTA ── */
    'cta.h2':  'Ready to sell without the fees?',
    'cta.p':   'Join hundreds of German sellers who&#39;ve taken control. List your place today and keep every euro of your sale price.',
    'cta.btn': 'List Your Place — Free to Start',

    /* ── SERVICES PAGE ── */
    'sp.hero.tag':    'Services &amp; Pricing',
    'sp.hero.h2':     'Pick exactly what you need',
    'sp.hero.p':      'Professional services, transparent fees. No forced bundles, no hidden charges, no commission.',
    'sp.addons.h2':   'Add-on Services',
    'sp.addons.p':    'Enhance your listing with professional add-ons — available &agrave; la carte or as part of a package.',
    'sp.s1.h3':  'Professional Photography',
    'sp.s1.p':   'Local professional photographers, same-week availability, edited high-res images delivered within 24 hours. Hero image rules included.',
    'sp.s1.price': '&#8364;149',
    'sp.s2.h3':  '360° Virtual Tour',
    'sp.s2.p':   'Matterport-style 3D scan of your property. Buyers explore every room before booking — fewer wasted viewings, higher-quality leads.',
    'sp.s2.price': '&#8364;199',
    'sp.s3.h3':  'Floorplan Creation',
    'sp.s3.p':   'Accurate publication-ready floorplans measured on-site. Required by portals for premium placement — buyers spend 52% longer on listings with floorplans.',
    'sp.s3.price': '&#8364;79',
    'sp.s4.h3':  'Legal Support',
    'sp.s4.p':   'Notary referrals, contract review guidance, and step-by-step document checklists at each legal milestone — from sale agreement to completion.',
    'sp.s4.price': 'from &#8364;299',
    'sp.s5.h3':  'For Sale Board',
    'sp.s5.p':   'Branded Yalla.House yard sign delivered and installed by a local partner. Still the #1 local lead generator — don&#39;t underestimate foot traffic.',
    'sp.s5.price': '&#8364;49',
    'sp.s6.h3':  'Portal Advertising',
    'sp.s6.p':   'Full listings on Rightmove and Zoopla. Automatic status sync, enhanced listing upgrades, and Yalla dashboard integration included.',
    'sp.s6.price': 'included',
    'sp.s7.h3':  'Hands-On Support',
    'sp.s7.p':   'Dedicated Yalla advisor to handle buyer queries, negotiate on your behalf, and guide you through the sale. Human help when you need it.',
    'sp.s7.price': '&#8364;499',
    'sp.s8.h3':  'Weekly Progress Reports',
    'sp.s8.p':   'Auto-generated seller update every 7 days: enquiries, viewings, feedback, offer status, and next steps — zero chasing required.',
    'sp.s8.price': 'included',
    'sp.s9.h3':  'Viewing Calendar',
    'sp.s9.p':   'Set live availability slots. Buyers self-book, confirm with one tap. Reduce viewing no-shows by up to 40%. Integrated with your dashboard.',
    'sp.s9.price': 'included',
    'sp.btn.add':      'Add to Listing',
    'sp.badge.incl':   'Included in all plans',
    'sp.pricing.tag':  'Pricing',
    'sp.pricing.h2':   'Simple, flat-fee plans',
    'sp.pricing.p':    'No percentages. No commission. Pay once, sell for any price.',
    'sp.plan1.name':   'Starter',
    'sp.plan1.price':  '&#8364;199 <span>one-time</span>',
    'sp.plan1.desc':   'Everything you need to get listed and sell yourself.',
    'sp.plan1.f1':     'Rightmove &amp; Zoopla listing',
    'sp.plan1.f2':     'Yalla.House seller dashboard',
    'sp.plan1.f3':     'Viewing calendar &amp; self-booking',
    'sp.plan1.f4':     'Weekly progress reports',
    'sp.plan1.f5':     'Offer management &amp; log',
    'sp.plan1.f6':     'Document storage',
    'sp.plan1.btn':    'Get Started',
    'sp.plan2.badge':  'Most popular',
    'sp.plan2.name':   'Professional',
    'sp.plan2.price':  '&#8364;499 <span>one-time</span>',
    'sp.plan2.desc':   'Professional media and portal presence to maximise your sale.',
    'sp.plan2.f1':     'Everything in Starter',
    'sp.plan2.f2':     'Professional photography',
    'sp.plan2.f3':     'Floorplan creation',
    'sp.plan2.f4':     'For Sale board',
    'sp.plan2.f5':     'Enhanced portal listing',
    'sp.plan2.f6':     'Energy certificate (EPC) booking assistance',
    'sp.plan2.f7':     'Priority support (2h SLA)',
    'sp.plan2.btn':    'Get Started',
    'sp.plan3.name':   'Complete',
    'sp.plan3.price':  '&#8364;899 <span>one-time</span>',
    'sp.plan3.desc':   'Full service — everything handled, from media to legal close.',
    'sp.plan3.f1':     'Everything in Professional',
    'sp.plan3.f2':     '360° Virtual Tour',
    'sp.plan3.f3':     'Dedicated Yalla advisor',
    'sp.plan3.f4':     'Legal support &amp; notary referral',
    'sp.plan3.f5':     'Negotiation assistance',
    'sp.plan3.f6':     'Completion checklist &amp; sign-off',
    'sp.plan3.f7':     'Priority support (1h SLA)',
    'sp.plan3.btn':    'Get Started',
    'sp.help.p':       'Not sure which plan to choose? <a href="mailto:support@yalla.house" style="color:var(--text-primary);font-weight:600;text-decoration:underline;text-underline-offset:3px;">Talk to us</a> — we&#39;ll recommend the right fit for your property.',
    'sp.vs.tag':       'Yalla vs Traditional Agent',
    'sp.vs.h2':        'The numbers don&#39;t lie',
    'sp.vs.p':         'On a &#8364;400,000 property, traditional German agents typically charge 3–6% commission.',
    'sp.vs.agent':     'Traditional Agent',
    'sp.vs.agent.v':   '&#8364;16,000+',
    'sp.vs.agent.p':   'Average commission on a &#8364;400k sale at 4%',
    'sp.vs.yalla':     'Yalla.House',
    'sp.vs.yalla.v':   '&#8364;199–&#8364;899',
    'sp.vs.yalla.p':   'Complete service at a flat fee — you save &#8364;15,000+',
    'sp.vs.save':      'You save',
    'sp.vs.save.v':    '&#8364;15,100+',
    'sp.vs.save.p':    'Goes straight back into your pocket — or your next purchase',
    'sp.cta.h2':       'Start listing — free to create your account',
    'sp.cta.p':        'Set up your property in minutes. Choose your plan when you&#39;re ready to go live.',
    'sp.cta.btn':      'List Your Place',

    /* ── ABOUT PAGE ── */
    'ab.mission.tag':  'Our Mission',
    'ab.h1':           'Property sales that are<br /><span>fair, clear, and yours</span>.',
    'ab.p':            'Yalla.House was built on a simple belief: selling your home should not cost you thousands of euros in commission. We&#39;ve stripped back the old model — and replaced it with transparency, technology, and tools that actually help.',
    'ab.trust1':       'Registered in Germany',
    'ab.trust2':       'GDPR Compliant',
    'ab.trust3':       'Listed on Rightmove &amp; Zoopla',
    'ab.trust4':       '5-Star Owner Satisfaction',
    'ab.trust5':       'No Commission. Ever.',
    'ab.why.tag':      'Why Yalla.House Exists',
    'ab.why.h2':       'The property market was broken.<br />So we fixed it.',
    'ab.why.p1':       'Traditional estate agents charge 3–6% commission on your sale price. On a &#8364;400,000 home, that&#39;s &#8364;16,000+ — for services that haven&#39;t meaningfully changed in decades.',
    'ab.why.p2':       'Meanwhile, sellers were chasing their agents for updates. Buyers were booking viewings for homes already reserved. Offers were logged on sticky notes. It was chaos — and everyone was paying for it.',
    'ab.why.p3':       'Yalla.House changes all of this. We built the tools agents should have built — and made them available to everyone, at a fraction of the cost.',
    'ab.diff.tag':     'What We Do Differently',
    'ab.diff.h2':      'Built on clarity, not commission',
    'ab.diff.p':       'Every feature we build answers the same question: does this make the seller or buyer&#39;s life measurably better?',
    'ab.v1.h4':        'Flat Fees, Always',
    'ab.v1.p':         'No percentage. No tiered commissions. You pay once, and keep every euro of your sale price — no matter what it sells for.',
    'ab.v2.h4':        'Weekly Progress, Automatic',
    'ab.v2.p':         'Every seller receives a co-branded weekly update covering enquiries, viewings, feedback, and next steps. No chasing required.',
    'ab.v3.h4':        'Live Viewing Slots',
    'ab.v3.p':         'You set when you&#39;re available. Buyers self-book confirmed slots — no email ping-pong, no double-booking, no no-shows.',
    'ab.v4.h4':        'Transparent Offer Management',
    'ab.v4.p':         'Every offer is logged with timestamp, buyer status, proof of funds, and chain details. You see everything in real time.',
    'ab.v5.h4':        'Real-Time Portal Sync',
    'ab.v5.p':         'Status changes update across Rightmove, Zoopla, and OnTheMarket automatically — no ghost listings, no stale data.',
    'ab.v6.h4':        'Secure &amp; Compliant',
    'ab.v6.p':         'All data handled in line with EU GDPR. FCA-regulated payment partners. KYC/KYB verification for verified buyers and sellers.',
    'ab.code.tag':     'Our Standards',
    'ab.code.h2':      'The Yalla Code of Clarity',
    'ab.code.p':       'Every listing on Yalla.House operates under these commitments — measurable, automatic, no exceptions.',
    'ab.cta.h2':       'Ready to take control of your sale?',
    'ab.cta.p':        'Join the sellers who&#39;ve already saved thousands. Your property. Your terms. Your price.',
    'ab.cta.btn':      'List Your Place — Free to Start',

    /* ── LIST WIZARD PAGE ── */
    'lp.step1.tag':    'Step 1 of 4',
    'lp.step1.h2':     'Tell us about your property',
    'lp.step2.tag':    'Step 2 of 4',
    'lp.step2.h2':     'Upload photos &amp; media',
    'lp.step3.tag':    'Step 3 of 4',
    'lp.step3.h2':     'Choose your services',
    'lp.step4.tag':    'Step 4 of 4',
    'lp.step4.h2':     'Review &amp; go live',
    'lp.back':         '&#8592; Back',
    'lp.next':         'Next &#8594;',
    'lp.submit':       'Submit Listing',
    /* ── SHARED DASHBOARD ── */
    'dnav.label.main':  'Main',
    'dnav.label.tools': 'Tools',
    'dnav.dashboard':   'Dashboard',
    'dnav.settings':    'Settings',
    'dnav.inbox':       'Inbox',
    /* ── OWNER DASHBOARD ── */
    'dash.nav.listings':  'My Listings',
    'dash.nav.inquiries': 'Buyer Inquiries',
    'dash.nav.analytics': 'Analytics',
    'dash.nav.documents': 'Documents',
    'dash.nav.calendar':  'Viewing Calendar',
    'dash.new':           '+ New Listing',
    'dash.role':          'Owner',
    /* ── BUYER DASHBOARD ── */
    'buyer.nav.search':   'Search',
    'buyer.nav.saved':    'Saved',
    'buyer.nav.viewings': 'My Viewings',
    'buyer.nav.offers':   'My Offers',
    'buyer.role':         'Home Hunter',
    /* ── ADMIN DASHBOARD ── */
    'admin.nav.overview':     'Overview',
    'admin.nav.listings':     'All Listings',
    'admin.nav.users':        'Users',
    'admin.nav.revenue':      'Revenue',
    'admin.nav.integrations': 'Integrations',
    'admin.role':             'Yalla Admin',
    /* ── AGENT DASHBOARD ── */
    'agent.nav.jobs':      'My Jobs',
    'agent.nav.completed': 'Completed',
    'agent.nav.earnings':  'Earnings',
    'agent.role':          'Street Team',
    /* ── PARTNER DASHBOARD ── */
    'partner.nav.requests': 'Referral Requests',
    'partner.nav.clients':  'My Clients',
    'partner.nav.earnings': 'Earnings',
    'partner.role':         'Partner Agent',
    /* ── REFERRER DASHBOARD ── */
    'ref.nav.overview':  'Overview',
    'ref.nav.referrals': 'My Referrals',
    'ref.nav.payouts':   'Payouts',
    'ref.role':          'Referrer',
  },

  /* ══════════════════════════════════════════════════════════
     GERMAN
  ══════════════════════════════════════════════════════════ */
  de: {
    'nav.services':         'Leistungen &amp; Preise',
    'nav.about':            '&#220;ber uns',
    'nav.list':             'Jetzt inserieren',
    'nav.signin':           'Anmelden &#9662;',
    'menu.label':           'Anmelden als',
    'menu.owner.name':      'Eigent&#252;mer / Verk&#228;ufer',
    'menu.owner.desc':      'Inserate, Besichtigungen &amp; Angebote',
    'menu.hunter.name':     'Wohnungssucher',
    'menu.hunter.desc':     'Durchsuchen &amp; Besichtigungen buchen',
    'menu.admin.name':      'Admin',
    'menu.admin.desc':      'Plattformverwaltung',
    'menu.agent.name':      'Au&#223;endienstmitarbeiter',
    'menu.agent.desc':      'Jobs &amp; Vor-Ort-Berichte',
    'footer.tagline':       'Keine Geb&#252;hren. Keine Provision.',
    'footer.meta':          'Yalla.House GmbH<br />Eingetragen in Deutschland.',
    'footer.col1.h4':       'Richtlinien',
    'footer.privacy':       'Datenschutzrichtlinie',
    'footer.terms':         'Nutzungsbedingungen',
    'footer.cookie':        'Cookie-Richtlinie',
    'footer.col2.h4':       'Recht &amp; Compliance',
    'footer.gdpr':          'DSGVO &amp; Sicherheit',
    'footer.security':      'Sicherheit &amp; Datenschutz',
    'footer.imprint':       'Impressum',
    'footer.col3.h4':       'Kontakt',
    'footer.copyright':     '&#169; 2025 Yalla.House GmbH. Alle Rechte vorbehalten.',
    'footer.portals':       'Inseriert auf Rightmove &bull; Zoopla',

    /* ── INDEX — Hero ── */
    'hero.badge':           'Jetzt live in Deutschland',
    'hero.h1':              'Verkaufen Sie Ihr Zuhause.<br />Behalten Sie jeden <span class="accent">Euro</span>.',
    'hero.p':               'Keine Maklergeb&#252;hren. Keine Provision. Professionelle Tools, echte K&#228;ufer und volle Kontrolle — f&#252;r eine pauschale, transparente Geb&#252;hr.',
    'hero.proof1':          '<strong>400+</strong> Verk&#228;ufer in Deutschland',
    'hero.proof2':          'Inseriert auf <strong>Rightmove &amp; Zoopla</strong>',
    'hero.proof3':          '<strong>5&#9733;</strong> Verk&#228;uferzufriedenheit',
    'login.title':          'In Dashboard anmelden',
    'login.owner.name':     'Eigent&#252;mer / Verk&#228;ufer',
    'login.owner.desc':     'Inserate, Besichtigungen &amp; Angebote verwalten',
    'login.hunter.name':    'Wohnungssucher',
    'login.hunter.desc':    'Immobilien durchsuchen &amp; Besichtigungen buchen',
    'login.admin.name':     'Admin',
    'login.admin.desc':     'Plattformverwaltung &amp; &#220;bersicht',
    'login.agent.name':     'Au&#223;endienstmitarbeiter',
    'login.agent.desc':     'Jobs, Besichtigungen &amp; Vor-Ort-Berichte',
    'login.new':            'Neu? Konto erstellen &#8594;',
    'portals.label':        'Inseriert auf',

    /* ── INDEX — Stats ── */
    'stat1.value':   '&#8364;0',
    'stat1.label':   'Provision — Sie behalten 100% Ihres Verkaufspreises',
    'stat2.value':   '48h',
    'stat2.label':   'Durchschnittliche Zeit bis zur Ver&#246;ffentlichung auf Rightmove &amp; Zoopla',
    'stat3.value':   '69%',
    'stat3.label':   'Der Verk&#228;ufer w&#252;nschen w&#246;chentliche automatische Fortschrittsupdates',
    'stat4.value':   '&#8364;8.000+',
    'stat4.label':   'Durchschnittliche Ersparnis gegen&#252;ber traditionellen Maklern bei &#8364;400.000 Verkauf',

    /* ── INDEX — How it works ── */
    'hiw.tag':    'So funktioniert es',
    'hiw.h2':    'Vom Inserat bis zum Verkauf — in vier Schritten',
    'hiw.p':     'Ein klarer, maklerfreier Prozess. Sie behalten die Kontrolle in jeder Phase.',
    'step1.h4':  'Jetzt inserieren',
    'step1.p':   'Beantworten Sie einige einfache Fragen. Fotos hochladen, Details hinzuf&#252;gen und Leistungen ausw&#228;hlen — in unter 20 Minuten.',
    'step2.h4':  'Auf Portalen live gehen',
    'step2.p':   'Ihre Immobilie erscheint auf Rightmove, Zoopla und mehr. Wir synchronisieren Status&#228;nderungen automatisch — keine Geisterlisten.',
    'step3.h4':  'Besichtigungen &amp; Angebote verwalten',
    'step3.p':   'K&#228;ufer buchen direkt aus Ihren Verf&#252;gbarkeitsterminen. Angebote im Dashboard pr&#252;fen mit voller Transparenz.',
    'step4.h4':  'Den Verkauf abschlie&#223;en',
    'step4.p':   'Rechtliche Unterst&#252;tzung, Dokumentenspeicherung und eine Abschluss-Checkliste — alles, was Sie zum Notartermin brauchen.',
    'step5.h4':  'Leistung &#252;berwachen',
    'step5.p':   'W&#246;chentliche Updates, K&#228;uferdaten, Antwortzeiten der Makler. Sehen Sie genau, was mit Ihrem Verkauf passiert.',
    'step6.h4':  'Den Abschluss machen',
    'step6.p':   'Dokumente, Meilensteine, rechtliche &#220;bergabe — alles f&#252;r einen reibungslosen Notartermin.',

    /* ── INDEX — Services ── */
    'svc.tag':  'Leistungen',
    'svc.h2':   'Alles, was Sie zum Verkaufen brauchen',
    'svc.p':    'W&#228;hlen Sie genau das, was Sie brauchen. Keine aufgezwungenen Pakete.',
    'svc1.h3':  'Professionelle Fotografie',
    'svc1.p':   'Hochwertige Immobilienfotos von lokalen Profis. Hero-Bild-Regeln f&#252;r maximale Portal-Klickrate inklusive.',
    'svc2.h3':  '360° Virtueller Rundgang',
    'svc2.p':   'Interaktiver 3D-Scan, damit K&#228;ufer Ihr Zuhause vor der Buchung erkunden k&#246;nnen — weniger verschwendete Besichtigungen.',
    'svc3.h3':  'Grundriss-Erstellung',
    'svc3.p':   'Genaue, ver&#246;ffentlichungsfertige Grundrisse. F&#252;r Premium-Platzierung auf Portalen erforderlich.',
    'svc4.h3':  'Rechtliche Unterst&#252;tzung',
    'svc4.p':   'Notar-Empfehlungen, Dokumentenpr&#252;fung und Begleitung an jedem rechtlichen Meilenstein.',
    'svc5.h3':  'Verkaufsschild',
    'svc5.p':   'Gebrandetes Schild — geliefert und installiert. Noch immer der #1 lokale Lead-Generator.',
    'svc6.h3':  'W&#246;chentliche Fortschrittsberichte',
    'svc6.p':   'Automatisch generiertes Verk&#228;ufer-Update alle 7 Tage — Anfragen, Besichtigungen, Feedback und n&#228;chste Schritte.',
    'svc.cta':  'Alle Leistungen &amp; Preise ansehen',

    /* ── INDEX — Clarity Index ── */
    'clarity.tag':      'Yalla Clarity Index',
    'clarity.h2':       'Was Verk&#228;ufer &amp; K&#228;ufer wirklich erleben',
    'clarity.p':        'Umfrage unter 400 deutschen Immobilienverk&#228;ufern — die Schmerzpunkte, die Yalla.House beseitigt.',
    'clarity1.p':       'der K&#228;ufer sagen, langsame oder keine Antwort ist ihre #1 Frustration',
    'clarity2.p':       'stie&#223;en auf &#8222;Geisterstatus&#8220; — als verf&#252;gbar gelistete Immobilien, die bereits reserviert waren',
    'clarity3.p':       'der Verk&#228;ufer f&#252;hlten sich &#8222;im Dunkeln&#8220; dar&#252;ber, was w&#246;chentlich passiert',
    'clarity4.suffix':  'Min',
    'clarity4.p':       'pro Verk&#228;ufer pro Woche gespart dank automatischer w&#246;chentlicher Updates',

    /* ── INDEX — Testimonials ── */
    'test.tag':    'Was andere sagen',
    'test.h2':     'Die Erfahrung spricht f&#252;r sich',
    'test1.q':     'Wenn ich einfach einen Termin w&#228;hlen k&#246;nnte, der tats&#228;chlich verf&#252;gbar ist, w&#252;rde ich doppelt so viele Wohnungen besichtigen. Yalla hat das endlich m&#246;glich gemacht.',
    'test1.name':  'Jan M.',
    'test1.role':  'Wohnungssucher, 32 — Berlin',
    'test2.q':     'Schick mir einen w&#246;chentlichen &#220;berblick, damit ich nicht nachfragen muss. Das ist alles, was ich will. Yalla macht das automatisch — ein Wendepunkt.',
    'test2.name':  'Sarah H.',
    'test2.role':  'Verk&#228;uferin, 48 — M&#252;nchen',
    'test3.q':     'Ich habe &#252;ber &#8364;12.000 an Maklergeb&#252;hren gespart. Die Portalinserate waren in 48 Stunden live und das Dashboard ist brilliant.',
    'test3.name':  'Ravi P.',
    'test3.role':  'Verk&#228;ufer, 41 — Frankfurt',

    /* ── INDEX — CTA ── */
    'cta.h2':  'Bereit, ohne Geb&#252;hren zu verkaufen?',
    'cta.p':   'Schlie&#223;en Sie sich Hunderten deutschen Verk&#228;ufern an, die die Kontrolle &#252;bernommen haben. Inserieren Sie noch heute und behalten Sie jeden Euro Ihres Verkaufspreises.',
    'cta.btn': 'Jetzt inserieren — kostenlos starten',

    /* ── SERVICES PAGE ── */
    'sp.hero.tag':    'Leistungen &amp; Preise',
    'sp.hero.h2':     'W&#228;hlen Sie genau das, was Sie brauchen',
    'sp.hero.p':      'Professionelle Leistungen, transparente Preise. Keine aufgezwungenen Pakete, keine versteckten Geb&#252;hren, keine Provision.',
    'sp.addons.h2':   'Zusatzleistungen',
    'sp.addons.p':    'Verbessern Sie Ihr Inserat mit professionellen Extras — einzeln oder als Paket buchbar.',
    'sp.s1.h3':  'Professionelle Fotografie',
    'sp.s1.p':   'Lokale Profifotografen, Verf&#252;gbarkeit in der gleichen Woche, bearbeitete hochaufl&#246;sende Bilder innerhalb von 24 Stunden. Hero-Bild-Regeln inklusive.',
    'sp.s1.price': '&#8364;149',
    'sp.s2.h3':  '360° Virtueller Rundgang',
    'sp.s2.p':   'Matterport-&#228;hnlicher 3D-Scan Ihrer Immobilie. K&#228;ufer erkunden jeden Raum vor der Buchung — weniger verschwendete Besichtigungen, hochwertigere Leads.',
    'sp.s2.price': '&#8364;199',
    'sp.s3.h3':  'Grundriss-Erstellung',
    'sp.s3.p':   'Genaue, ver&#246;ffentlichungsfertige Grundrisse, vor Ort vermessen. F&#252;r Premium-Platzierung auf Portalen erforderlich — K&#228;ufer verbringen 52% l&#228;nger auf Inseraten mit Grundrissen.',
    'sp.s3.price': '&#8364;79',
    'sp.s4.h3':  'Rechtliche Unterst&#252;tzung',
    'sp.s4.p':   'Notar-Empfehlungen, Vertragsprüfungsberatung und Schritt-f&#252;r-Schritt-Dokumentenchecklisten an jedem rechtlichen Meilenstein — vom Kaufvertrag bis zum Abschluss.',
    'sp.s4.price': 'ab &#8364;299',
    'sp.s5.h3':  'Verkaufsschild',
    'sp.s5.p':   'Gebrandetes Yalla.House-Schild von einem lokalen Partner geliefert und installiert. Noch immer der #1 lokale Lead-Generator.',
    'sp.s5.price': '&#8364;49',
    'sp.s6.h3':  'Portalwerbung',
    'sp.s6.p':   'Vollst&#228;ndige Inserate auf Rightmove und Zoopla. Automatische Statussynchronisierung, verbesserte Inserat-Upgrades und Yalla-Dashboard-Integration inklusive.',
    'sp.s6.price': 'inklusive',
    'sp.s7.h3':  'Pers&#246;nliche Unterst&#252;tzung',
    'sp.s7.p':   'Dedizierter Yalla-Berater f&#252;r K&#228;uferanfragen, Verhandlungen und Begleitung durch den Verkauf. Menschliche Hilfe, wenn Sie sie brauchen.',
    'sp.s7.price': '&#8364;499',
    'sp.s8.h3':  'W&#246;chentliche Fortschrittsberichte',
    'sp.s8.p':   'Automatisch generiertes Verk&#228;ufer-Update alle 7 Tage: Anfragen, Besichtigungen, Feedback, Angebotsstatus und n&#228;chste Schritte — ohne Nachfragen.',
    'sp.s8.price': 'inklusive',
    'sp.s9.h3':  'Besichtigungskalender',
    'sp.s9.p':   'Verf&#252;gbarkeitsslots festlegen. K&#228;ufer buchen selbst, best&#228;tigen mit einem Tipp. Besichtigungs-No-Shows um bis zu 40% reduzieren. Im Dashboard integriert.',
    'sp.s9.price': 'inklusive',
    'sp.btn.add':      'Zum Inserat hinzuf&#252;gen',
    'sp.badge.incl':   'In allen Pl&#228;nen enthalten',
    'sp.pricing.tag':  'Preise',
    'sp.pricing.h2':   'Einfache Pauschalpreispl&#228;ne',
    'sp.pricing.p':    'Keine Prozents&#228;tze. Keine Provision. Einmal zahlen, zum beliebigen Preis verkaufen.',
    'sp.plan1.name':   'Starter',
    'sp.plan1.price':  '&#8364;199 <span>einmalig</span>',
    'sp.plan1.desc':   'Alles, was Sie brauchen, um zu inserieren und selbst zu verkaufen.',
    'sp.plan1.f1':     'Rightmove &amp; Zoopla Inserat',
    'sp.plan1.f2':     'Yalla.House Verk&#228;ufer-Dashboard',
    'sp.plan1.f3':     'Besichtigungskalender &amp; Selbstbuchung',
    'sp.plan1.f4':     'W&#246;chentliche Fortschrittsberichte',
    'sp.plan1.f5':     'Angebotsverwaltung &amp; Protokoll',
    'sp.plan1.f6':     'Dokumentenspeicherung',
    'sp.plan1.btn':    'Jetzt starten',
    'sp.plan2.badge':  'Beliebteste Wahl',
    'sp.plan2.name':   'Professional',
    'sp.plan2.price':  '&#8364;499 <span>einmalig</span>',
    'sp.plan2.desc':   'Professionelle Medien und Portalpräsenz f&#252;r maximalen Verkaufserfolg.',
    'sp.plan2.f1':     'Alles aus Starter',
    'sp.plan2.f2':     'Professionelle Fotografie',
    'sp.plan2.f3':     'Grundriss-Erstellung',
    'sp.plan2.f4':     'Verkaufsschild',
    'sp.plan2.f5':     'Erweitertes Portalinserat',
    'sp.plan2.f6':     'Energieausweis-Buchungsassistenz',
    'sp.plan2.f7':     'Priorit&#228;ts-Support (2h SLA)',
    'sp.plan2.btn':    'Jetzt starten',
    'sp.plan3.name':   'Komplett',
    'sp.plan3.price':  '&#8364;899 <span>einmalig</span>',
    'sp.plan3.desc':   'Rundum-Service — von den Medien bis zum notariellen Abschluss.',
    'sp.plan3.f1':     'Alles aus Professional',
    'sp.plan3.f2':     '360° Virtueller Rundgang',
    'sp.plan3.f3':     'Dedizierter Yalla-Berater',
    'sp.plan3.f4':     'Rechtliche Unterst&#252;tzung &amp; Notar-Empfehlung',
    'sp.plan3.f5':     'Verhandlungsassistenz',
    'sp.plan3.f6':     'Abschluss-Checkliste &amp; Freigabe',
    'sp.plan3.f7':     'Priorit&#228;ts-Support (1h SLA)',
    'sp.plan3.btn':    'Jetzt starten',
    'sp.help.p':       'Nicht sicher, welchen Plan Sie w&#228;hlen sollen? <a href="mailto:support@yalla.house" style="color:var(--text-primary);font-weight:600;text-decoration:underline;text-underline-offset:3px;">Sprechen Sie mit uns</a> — wir empfehlen das Richtige f&#252;r Ihre Immobilie.',
    'sp.vs.tag':       'Yalla vs. Traditioneller Makler',
    'sp.vs.h2':        'Die Zahlen l&#252;gen nicht',
    'sp.vs.p':         'Bei einer Immobilie im Wert von &#8364;400.000 berechnen traditionelle Makler typischerweise 3–6% Provision.',
    'sp.vs.agent':     'Traditioneller Makler',
    'sp.vs.agent.v':   '&#8364;16.000+',
    'sp.vs.agent.p':   'Durchschnittliche Provision bei &#8364;400k Verkauf (4%)',
    'sp.vs.yalla':     'Yalla.House',
    'sp.vs.yalla.v':   '&#8364;199–&#8364;899',
    'sp.vs.yalla.p':   'Komplettservice zum Pauschalpreis — Sie sparen &#8364;15.000+',
    'sp.vs.save':      'Sie sparen',
    'sp.vs.save.v':    '&#8364;15.100+',
    'sp.vs.save.p':    'Landet direkt in Ihrer Tasche — oder finanziert Ihr n&#228;chstes Zuhause',
    'sp.cta.h2':       'Jetzt inserieren — kostenloses Konto erstellen',
    'sp.cta.p':        'Richten Sie Ihre Immobilie in Minuten ein. W&#228;hlen Sie Ihren Plan, wenn Sie bereit sind, live zu gehen.',
    'sp.cta.btn':      'Jetzt inserieren',

    /* ── ABOUT PAGE ── */
    'ab.mission.tag':  'Unsere Mission',
    'ab.h1':           'Immobilienverkäufe die<br /><span>fair, klar und Ihnen geh&#246;ren</span>.',
    'ab.p':            'Yalla.House basiert auf einer einfachen &#220;berzeugung: Der Verkauf Ihres Hauses sollte Sie nicht Tausende von Euro Provision kosten. Wir haben das alte Modell abgel&#246;st — und es durch Transparenz, Technologie und Tools ersetzt, die wirklich helfen.',
    'ab.trust1':       'Eingetragen in Deutschland',
    'ab.trust2':       'DSGVO-konform',
    'ab.trust3':       'Inseriert auf Rightmove &amp; Zoopla',
    'ab.trust4':       '5-Sterne-Verk&#228;uferzufriedenheit',
    'ab.trust5':       'Keine Provision. Niemals.',
    'ab.why.tag':      'Warum Yalla.House existiert',
    'ab.why.h2':       'Der Immobilienmarkt war kaputt.<br />Also haben wir ihn repariert.',
    'ab.why.p1':       'Traditionelle Makler berechnen 3–6% Provision auf Ihren Verkaufspreis. Bei einer Immobilie im Wert von &#8364;400.000 sind das &#8364;16.000+ — f&#252;r Leistungen, die sich seit Jahrzehnten nicht wesentlich ver&#228;ndert haben.',
    'ab.why.p2':       'Inzwischen mussten Verk&#228;ufer ihren Maklern hinterherlaufen. K&#228;ufer buchten Besichtigungen f&#252;r bereits reservierte Immobilien. Angebote wurden auf Haftnotizen vermerkt. Es war Chaos — und alle zahlten daf&#252;r.',
    'ab.why.p3':       'Yalla.House &#228;ndert das alles. Wir haben die Tools gebaut, die Makler h&#228;tten bauen sollen — und sie f&#252;r alle zug&#228;nglich gemacht, zu einem Bruchteil der Kosten.',
    'ab.diff.tag':     'Was wir anders machen',
    'ab.diff.h2':      'Gebaut auf Klarheit, nicht auf Provision',
    'ab.diff.p':       'Jede Funktion, die wir entwickeln, beantwortet dieselbe Frage: Macht das das Leben des Verk&#228;ufers oder K&#228;ufers messbar besser?',
    'ab.v1.h4':        'Pauschalpreise, immer',
    'ab.v1.p':         'Kein Prozentsatz. Keine gestaffelten Provisionen. Sie zahlen einmal und behalten jeden Euro Ihres Verkaufspreises — egal zu welchem Preis Sie verkaufen.',
    'ab.v2.h4':        'W&#246;chentlicher Fortschritt, automatisch',
    'ab.v2.p':         'Jeder Verk&#228;ufer erh&#228;lt ein w&#246;chentliches Update mit Anfragen, Besichtigungen, Feedback und n&#228;chsten Schritten. Kein Nachfragen erforderlich.',
    'ab.v3.h4':        'Live-Besichtigungsslots',
    'ab.v3.p':         'Sie legen fest, wann Sie verf&#252;gbar sind. K&#228;ufer buchen best&#228;tigte Slots selbst — kein E-Mail-Ping-Pong, keine Doppelbuchungen, keine No-Shows.',
    'ab.v4.h4':        'Transparentes Angebotsmanagement',
    'ab.v4.p':         'Jedes Angebot wird mit Zeitstempel, K&#228;uferstatus, Finanzierungsnachweis und Kettendetails protokolliert. Sie sehen alles in Echtzeit.',
    'ab.v5.h4':        'Echtzeit-Portalsynchronisation',
    'ab.v5.p':         'Status&#228;nderungen werden automatisch auf Rightmove, Zoopla und OnTheMarket aktualisiert — keine Geisterlisten, keine veralteten Daten.',
    'ab.v6.h4':        'Sicher &amp; Konform',
    'ab.v6.p':         'Alle Daten werden gem&#228;&#223; EU-DSGVO verarbeitet. Regulierte Zahlungspartner. KYC/KYB-Verifizierung f&#252;r verifizierte K&#228;ufer und Verk&#228;ufer.',
    'ab.code.tag':     'Unsere Standards',
    'ab.code.h2':      'Der Yalla Code der Klarheit',
    'ab.code.p':       'Jedes Inserat auf Yalla.House operiert unter diesen Verpflichtungen — messbar, automatisch, keine Ausnahmen.',
    'ab.cta.h2':       'Bereit, die Kontrolle &#252;ber Ihren Verkauf zu &#252;bernehmen?',
    'ab.cta.p':        'Schlie&#223;en Sie sich den Verk&#228;ufern an, die bereits Tausende gespart haben. Ihre Immobilie. Ihre Bedingungen. Ihr Preis.',
    'ab.cta.btn':      'Jetzt inserieren — kostenlos starten',

    /* ── LIST WIZARD PAGE ── */
    'lp.step1.tag':    'Schritt 1 von 4',
    'lp.step1.h2':     'Erz&#228;hlen Sie uns von Ihrer Immobilie',
    'lp.step2.tag':    'Schritt 2 von 4',
    'lp.step2.h2':     'Fotos &amp; Medien hochladen',
    'lp.step3.tag':    'Schritt 3 von 4',
    'lp.step3.h2':     'Leistungen ausw&#228;hlen',
    'lp.step4.tag':    'Schritt 4 von 4',
    'lp.step4.h2':     '&#220;berpr&#252;fen &amp; live gehen',
    'lp.back':         '&#8592; Zur&#252;ck',
    'lp.next':         'Weiter &#8594;',
    'lp.submit':       'Inserat einreichen',
    /* ── SHARED DASHBOARD ── */
    'dnav.label.main':  'Hauptmen&#252;',
    'dnav.label.tools': 'Werkzeuge',
    'dnav.dashboard':   'Dashboard',
    'dnav.settings':    'Einstellungen',
    'dnav.inbox':       'Posteingang',
    /* ── OWNER DASHBOARD ── */
    'dash.nav.listings':  'Meine Inserate',
    'dash.nav.inquiries': 'K&#228;uferanfragen',
    'dash.nav.analytics': 'Statistiken',
    'dash.nav.documents': 'Dokumente',
    'dash.nav.calendar':  'Besichtigungskalender',
    'dash.new':           '+ Neues Inserat',
    'dash.role':          'Verk&#228;ufer',
    /* ── BUYER DASHBOARD ── */
    'buyer.nav.search':   'Suchen',
    'buyer.nav.saved':    'Gespeichert',
    'buyer.nav.viewings': 'Meine Besichtigungen',
    'buyer.nav.offers':   'Meine Angebote',
    'buyer.role':         'Wohnungssucher',
    /* ── ADMIN DASHBOARD ── */
    'admin.nav.overview':     '&#220;bersicht',
    'admin.nav.listings':     'Alle Inserate',
    'admin.nav.users':        'Benutzer',
    'admin.nav.revenue':      'Einnahmen',
    'admin.nav.integrations': 'Integrationen',
    'admin.role':             'Yalla Admin',
    /* ── AGENT DASHBOARD ── */
    'agent.nav.jobs':      'Meine Jobs',
    'agent.nav.completed': 'Abgeschlossen',
    'agent.nav.earnings':  'Verdienst',
    'agent.role':          'Au&#223;endienst',
    /* ── PARTNER DASHBOARD ── */
    'partner.nav.requests': 'Anfragen',
    'partner.nav.clients':  'Meine Kunden',
    'partner.nav.earnings': 'Verdienst',
    'partner.role':         'Partneragent',
    /* ── REFERRER DASHBOARD ── */
    'ref.nav.overview':  '&#220;bersicht',
    'ref.nav.referrals': 'Meine Empfehlungen',
    'ref.nav.payouts':   'Auszahlungen',
    'ref.role':          'Empfehler',
  }
};

/* ── Language detection ── */
function detectLang() {
  var stored = localStorage.getItem('yh_lang');
  if (stored === 'en' || stored === 'de') return stored;
  var browser = (navigator.language || navigator.userLanguage || 'en').toLowerCase();
  return browser.startsWith('de') ? 'de' : 'en';
}

/* ── Apply language ── */
function setLang(lang) {
  if (lang !== 'en' && lang !== 'de') lang = 'en';
  localStorage.setItem('yh_lang', lang);
  var t = TRANSLATIONS[lang];
  var els = document.querySelectorAll('[data-i18n]');
  for (var i = 0; i < els.length; i++) {
    var key = els[i].getAttribute('data-i18n');
    if (t[key] !== undefined) {
      els[i].innerHTML = t[key];
    }
  }
  /* Update switcher button states */
  var btnEn = document.getElementById('lang-btn-en');
  var btnDe = document.getElementById('lang-btn-de');
  if (btnEn) btnEn.classList.toggle('active', lang === 'en');
  if (btnDe) btnDe.classList.toggle('active', lang === 'de');
  /* Update html[lang] for accessibility */
  document.documentElement.lang = lang;
}

/* ── Init on load ── */
document.addEventListener('DOMContentLoaded', function () {
  setLang(detectLang());
});
